repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-yaml
    -   id: trailing-whitespace
-   repo: https://github.com/domluna/JuliaFormatter.jl
    rev: v1.0.43
    hooks:
    -   id: julia-formatter
